import { Link } from 'react-router-dom';
import { Block } from 'types';
import { dateFromTimestamp } from 'utils/dates';

type Props = {
  block: Block;
};

const BlockHeader = ({ block }: Props): React.ReactElement => {
  return (
    <div className="text-center">
      <h2 className="truncate text-secondary-400">{block.id}</h2>
      <p>
        Generated by{' '}
        <Link to={`/account/${block.generatorAddress}`} className="font-bold">
          {block.generatorUsername}
        </Link>{' '}
        on {dateFromTimestamp(block.timestamp)}
      </p>
    </div>
  );
};

export default BlockHeader;
